from __future__ import unicode_literals
from django.contrib import admin
from .models import *

admin.site.register(Department)
admin.site.register(Designation)
admin.site.register(Position)
admin.site.register(Request)
admin.site.register(Source)
admin.site.register(Candidate)
admin.site.register(CandidatePersonal)
admin.site.register(Courses)
admin.site.register(EducationalInstitution)
admin.site.register(CandidateEducation)
admin.site.register(CandidateProfessional)
admin.site.register(CandidateProcess)
admin.site.register(CandidateOffer)
admin.site.register(CandidateSkill)
admin.site.register(InterviewLevel)
admin.site.register(InterviewRound)
admin.site.register(Panellist)
admin.site.register(PanelMembersDirectory)
admin.site.register(EmailTemplates) 
admin.site.register(Skills)
admin.site.register(CandidateFeedback)
admin.site.register(Resume)
admin.site.register(CandidateCost)
admin.site.register(Estimates)
admin.site.register(CandidateEngagement)
admin.site.register(EngagementActions)
